# fly.toml app configuration file generated for club-reservation-service
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "club-reservation-service"
primary_region = "bos"  # Boston, MA

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "club_reservation_data"
  destination = "/data"
  snapshot_retention = 14

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
